import express from "express";
import router from "./router";
import morgan from "morgan";
import cors from "cors";
import { protect } from "../modules/auth";
const app = express();
app.use(cors());
app.use(morgan("dev"));
app.use(express.json());
app.use("/api/v1", protect, router);
export default app;
